my:
  name: -MohammedumerMujahid For Standalone Application
  greeting: Hello World from config server updated on 24 Jan 2025.
  list:
    values: One, Two, Three
    
db:
  connection: connection-string-here-from-config-server
  host: 127.0.0.1
  port: 1200

user:
  name: mohammed
  age: '40'

